// <auto-generated />
namespace Megatech.FMS.WebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class customRole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(customRole));
        
        string IMigrationMetadata.Id
        {
            get { return "202011300630427_customRole"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
